version : '3'

services:

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_ADMIN_USER=${MYSQL_ADMIN_USER}
        - MYSQL_ADMIN_PASSWORD=${MYSQL_ADMIN_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_volume:/var/db
    networks:
      - backend
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_ADMIN_USER=${MYSQL_ADMIN_USER}
        - MYSQL_ADMIN_PASSWORD=${MYSQL_ADMIN_PASSWORD}
        - DB_HOST=${DB_HOST}
        - MYSQL_USER=${MYSQL_USER}
        - WP_PATH=${WP_PATH}
    ports:
      - '9000:9000'
    volumes:
      - ./wordpress_volume:/var/www
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ADMIN_USER: ${MYSQL_ADMIN_USER}
      MYSQL_ADMIN_PASSWORD: ${MYSQL_ADMIN_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      WP_PATH: ${WP_PATH}
      DB_HOST: ${DB_HOST}
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    command: bash -c "/run/wp_start.sh && exec bash"
    restart: always

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      args:
        - DOMAIN=${DOMAIN}
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./wordpress_volume:/var/www
    depends_on:
      - wordpress
    networks:
      - frontend
    restart: unless-stopped

networks:
  frontend:
  backend:

volumes:
  mysql_volume:
    driver_opts:
      type: none
      device: "$HOME/data/mysql"
      o: bind
  wordpress_volume:
    driver_opts:
      type: none
      device: "$HOME/data/html"
      o: bind