version : '3'

services:

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    ports:
      - '443:443'
    depends_on:
      - wordpress
    networks:
      - custom-network
    restart: unless-stopped

  mysql:
    image: mariadb
    ports:
      - '3306:3306'
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=aqwe123
    restart: always

  wordpress:
    image: wordpress:4.7.1-php7.0-fpm
    ports:
      - '9000:9000'
    volumes:
      - ./wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=wpdb
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_PASSWORD=test
    links:
      - mysql
    restart: always

networks:
  custom-network: